version: "3.9"

services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    # command is optional if you have CMD in your Dockerfile
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

    extra_hosts:
      - "host.docker.internal:host-gateway"
