"""Add attributes to politician/bill association

Revision ID: 077624c0e64f
Revises: 4a0f83b4f4f2
Create Date: 2024-12-15 23:05:14.026619+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '077624c0e64f'
down_revision: Union[str, None] = '4a0f83b4f4f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('politicians', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('politicians', 'email')
    # ### end Alembic commands ###
