"""Add new fields and relationships

Revision ID: 238971668613
Revises: 077624c0e64f
Create Date: 2024-12-16 03:11:46.904903+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '238971668613'
down_revision: Union[str, None] = '077624c0e64f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('global_return_addresses')
    op.add_column('mailing_transactions', sa.Column('mail_service_response', sa.JSON(), nullable=True))
    op.add_column('user_letter_requests', sa.Column('use_profile_return_address', sa.Boolean(), server_default='true', nullable=False))
    op.drop_column('user_letter_requests', 'user_provided_name')
    op.drop_column('user_letter_requests', 'user_provided_city')
    op.drop_column('user_letter_requests', 'user_provided_address_line2')
    op.drop_column('user_letter_requests', 'user_provided_zip')
    op.drop_column('user_letter_requests', 'user_provided_state')
    op.drop_column('user_letter_requests', 'user_comments')
    op.drop_column('user_letter_requests', 'user_provided_address_line1')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_letter_requests', sa.Column('user_provided_address_line1', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_letter_requests', sa.Column('user_comments', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('user_letter_requests', sa.Column('user_provided_state', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_letter_requests', sa.Column('user_provided_zip', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_letter_requests', sa.Column('user_provided_address_line2', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_letter_requests', sa.Column('user_provided_city', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_letter_requests', sa.Column('user_provided_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user_letter_requests', 'use_profile_return_address')
    op.drop_column('mailing_transactions', 'mail_service_response')
    op.create_table('global_return_addresses',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organization_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('address_line1', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('address_line2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('zipcode', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='global_return_addresses_pkey')
    )
    # ### end Alembic commands ###
