"""Add additional profile fields to users

Revision ID: 4a0f83b4f4f2
Revises: 8d115d93aa0f
Create Date: 2024-12-15 20:09:34.163852+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a0f83b4f4f2'
down_revision: Union[str, None] = '8d115d93aa0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_complete', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('address_line1', sa.String(), nullable=True))
    op.add_column('users', sa.Column('address_line2', sa.String(), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(), nullable=True))
    op.add_column('users', sa.Column('state', sa.String(), nullable=True))
    op.add_column('users', sa.Column('zipcode', sa.String(), nullable=True))
    op.add_column('users', sa.Column('profile_photo', sa.LargeBinary(), nullable=True))
    op.add_column('users', sa.Column('thumbnail_photo', sa.LargeBinary(), nullable=True))
    op.add_column('users', sa.Column('personal_description', sa.String(), nullable=True))
    op.add_column('users', sa.Column('political_party', sa.String(), nullable=True))
    op.add_column('users', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('users', sa.Column('race', sa.String(), nullable=True))
    op.add_column('users', sa.Column('home_phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('cell_phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('occupation', sa.String(), nullable=True))
    op.add_column('users', sa.Column('employer', sa.String(), nullable=True))
    op.add_column('users', sa.Column('website_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('social_media_handles', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('preferred_contact_method', sa.String(), nullable=True))
    op.add_column('users', sa.Column('interests', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('preferred_language', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferred_language')
    op.drop_column('users', 'interests')
    op.drop_column('users', 'preferred_contact_method')
    op.drop_column('users', 'social_media_handles')
    op.drop_column('users', 'website_url')
    op.drop_column('users', 'employer')
    op.drop_column('users', 'occupation')
    op.drop_column('users', 'cell_phone')
    op.drop_column('users', 'home_phone')
    op.drop_column('users', 'race')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'date_of_birth')
    op.drop_column('users', 'political_party')
    op.drop_column('users', 'personal_description')
    op.drop_column('users', 'thumbnail_photo')
    op.drop_column('users', 'profile_photo')
    op.drop_column('users', 'zipcode')
    op.drop_column('users', 'state')
    op.drop_column('users', 'city')
    op.drop_column('users', 'address_line2')
    op.drop_column('users', 'address_line1')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'profile_complete')
    # ### end Alembic commands ###
