"""Add changes for queued letters and global return address

Revision ID: af2c67ec83b1
Revises: f15bcc3e4ba4
Create Date: 2024-12-16 04:39:42.495430+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af2c67ec83b1'
down_revision: Union[str, None] = 'f15bcc3e4ba4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queued_letters', 'final_letter_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queued_letters', sa.Column('final_letter_text', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
